version: '3.8'

services:
  kafka:
    image: docker.io/apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - otel-network
    volumes:
      - ./data/kafka:/var/lib/kafka/data:rw,z

  pinot:
    image: docker.io/apachepinot/pinot:1.4.0
    container_name: pinot-allinone
    command: QuickStart -type BATCH
    ports:
      - "9000:9000"   # Controller + Query endpoint
      - "8099:8099"   # Additional management port
    environment:
      # Forces Pinot's QuickStart to write its "temporary" data here instead of /tmp
      JAVA_OPTS: "-Djava.io.tmpdir=/opt/pinot/data"
    depends_on:
      - kafka
    networks:
      - otel-network
    volumes: 
      - ./data/pinot:/opt/pinot/data:rw,z
  

networks:
  otel-network:
    driver: bridge
