version: '3.8'

services:
  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    networks:
      - otel-network
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse:rw,z
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  perses:
    image: persesdev/perses:v0.53.1-debug
    name: perses
    ports:
      - "8082:8080"
    volumes:
      - ./data/perses:/perses


networks:
  otel-network:
    driver: bridge
